spring.application.name=Backend

# Overriding the data source for your cloud TiDB Database
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# This line automatically creates your tables in the cloud database
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Third-Party Weather API Authentication Keys
openweathermap.api.key=${OPENWEATHER_API_KEY:f5e923868577018c7a11ff3623dafb41}
weatherapi.key=${WEATHERAPI_KEY:4d2f4f3e0060493d95860505262705}

# 4. Outbound Mail Engine Server Parameters
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:skarthicpnp06@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:hkga wsea isqt ijbh}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 5. Security CORS Mapping Access Rules
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}