spring.application.name=Backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://bhan6nzyxfhly6se7hla-mysql.services.clever-cloud.com:3306/bhan6nzyxfhly6se7hla?useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ugks0d2e2sxpzsgf}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cEtRdzpMgj3juTytx3Z0}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

openweathermap.api.key=${OPENWEATHER_API_KEY:f5e923868577018c7a11ff3623dafb41}
weatherapi.key=${WEATHERAPI_KEY:4d2f4f3e0060493d95860505262705}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:skarthicpnp06@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:hkga wsea isqt ijbh}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://weather-dashboard-987s.vercel.app}

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000