# Step 1: Build the application using Maven
FROM maven:3.8.4-openjdk-17 AS build
COPY . .
RUN ./mvnw clean package -DskipTests

# Step 2: Run the built JAR file using lightweight Java runtime
FROM openjdk:17-jdk-slim
COPY --from=build /target/Backend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]